### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by jakobnissen** [aviatesk/JETLS.jl#274]
Again, please let me know if JETLS is too early in development for these bugreports to be usable.

This happens when opening `https://github.com/BioJulia/BGZFLib.jl` at commit e00e5d92 using JETLS from today.

#### Cannot identify package environment
Error:
```
[JETLS-stderr] ┌ Warning: Failed to identify package environment
[JETLS-stderr] │   pkgname = "BGZFLib"
[JETLS-stderr] └ @ JETLS ~/code/JETLS.jl/src/analysis/
```
Package has only registered dependencies, and is fully resolved and updated.
This occurs intermittently. All the other errors below also occur when this error does not happen.

#### False positive: Invalid function name
Error:
```
Invalid function nameJETLS - lowering
```
This is marked on the line `Base.:(<)(x::VirtualOffset, y::VirtualOffset) = getfield(x, :x) < getfield(y, :x)`

#### False positive: `Unused argument `io`JETLS - lowering`
In this function where `io` is clearly used:
```
function get_writer_sink_room(io::AbstractBufWriter)::MutableMemoryView{UInt8}
    buffer = get_buffer(io)
    while length(buffer) < MAX_BLOCK_SIZE
        n = grow_buffer(io)
        iszero(n) && throw(BGZFError(nothing, BGZFErrors.insufficient_writer_space))
        buffer = get_buffer(io)
    end
    return buffer
end
```
There are dozens of this false positive all over the code.

#### Highlighting does not track code when moved
If I add newlines, the highlighted areas do not move correspondingly. For example, when adding a newline abive the `get_writer_sink_room` function, it looks like this. Note the wrong placement of the blue underlines. The blue underline under `while ` is marked `Unused local binding `buffer`JETLS - lowering`.

<img width="425" height="257" alt="Image" src="https://github.com/user-attachments/assets/63833368-13f0-4c39-8dc6-89f855fd1932" />

#### Cache files not found
When opening a new file in the project, JETLS crashes with:
```
[Error - 13:18:59] Request textDocument/diagnostic failed.
  Message: File cache for file:///home/jakni/code/BGZFLib.jl/src/index.jl is not found
  Code: -32803 
[object Object]
[Error - 13:18:59] Document pull failed for text document file:///home/jakni/code/BGZFLib.jl/src/index.jl
  Message: File cache for file:///home/jakni/code/BGZFLib.jl/src/index.jl is not found
  Code: -32803 
[object Object]
```

**Comment by aviatesk** [comment]
> False positive: `Unused argument `io`JETLS - lowering`

This should be fixed on the latest master.

> Highlighting does not track code when moved

Isn't this issue just temporary?
In my client (Zed), diagnostics get updated pretty quickly when a newline is inserted, because `textDocument/diagnostic` is requested again. I confirmed similar behavior in my VSCode setup as well.

**Comment by aviatesk** [comment]
> please let me know if JETLS is too early in development for these bugreports to be usable.

It's definitely very early since JETLS isn't not ready for general use yet, but getting these issue reports is valuable even at this phase.

**Comment by aviatesk** [comment]
> False positive: Invalid function name

This will be fixed by #277

**Comment by clason** [comment]
> When opening a new file in the project, JETLS crashes with:

That also happens when reopening the _same_ file (at least in Neovim; just `:e`).

**Comment by aviatesk** [comment]
> #### Cache files not found
> 
> When opening a new file in the project, JETLS crashes with:

What's the actual problem here?
LSP doesn't have a strict order for requesting messages, so seeing those errors in the logs is expected behavior. It's only a problem if the server process crashes.

**Comment by clason** [comment]
Since these are hard errors, they are propagated to the client and shown in the editor.

**Comment by aviatesk** [comment]
It depends on how clients handle error responses, but I agree this kind of error shouldn't be reported as user-facing errors. The problem is that I can't really reproduce this error on my clients (VSCode, Zed). Any more specific reproducer?

**Comment by clason** [comment]
Simply use Neovim? ("Simply" means that this is enough to trigger the user error; I'm more than happy to help you set it up.)

Or even more simply, if it's not an error, don't log it as such -- the server has log levels, doesn't it? Should be Debug if such a cache miss is really expected.

**Comment by jakobnissen** [comment]
> Isn't this issue just temporary?

No, it does not change. Here is a video of it. Not shown in the video is that you can see JETLS reanalyses the file, but it has no effect on the highlighting.

https://github.com/user-attachments/assets/78c5a2cc-99c8-459a-8fb9-0a5baefdeff1

> What's the actual problem here?

I don't know if it's actually a problem. But I do get a pop-up saying "Request textDocument/diagnostic failed." with "Source: JETLS client"

**Comment by aviatesk** [comment]
> I don't know if it's actually a problem. But I do get a pop-up saying "Request textDocument/diagnostic failed." with "Source: JETLS client"

Did this happen in VSCode? Could you tell me about the file structure and the exact steps you took that caused this? I'd like to understand what's happening, rather than just suppressing the error.

**Comment by jakobnissen** [comment]
Yeah, here are some more details
* VSCode 1.105.1
* On Majaro Linux, VSCode installed from AUR
* Using Julia 1.12.0
* Latest JETLS extension (from Tuesday)
* The JETLS settings are:
```
    "jetls-client.communicationChannel": "auto",
    "jetls-client.jetlsDirectory": "/home/jakni/code/JETLS.jl",
    "jetls-client.juliaExecutablePath": "/home/jakni/.julia/juliaup/julia-1.12.0+0.x64.linux.gnu/bin/julia",
```

The way I can reproduce it is:
1. Open [BGZFLib.jl](https://github.com/BioJulia/BGZFLib.jl) at commit e00e5d92b
2. Wait for JETLS to fully load
3. Open the file explorer (Ctrl + Shift + E)
4. Click various files in the `src/` directory to open

It triggers _most_ of the time, but sometimes it takes clicking on more than one file before it triggers.

**Comment by aviatesk** [comment]
Most of the issues reported in this issue should be resolved in the 2025-11-30 release.
Regarding the "File cache not found" error, I still couldn't reproduce it on my end, so I haven't made any critical fixes.
Of course, it would be better to eliminate that possibility, but I don't want to remove errors symptomatically without figuring out the root cause of the problem, so I'm keeping it in the same state as before for now.
Note that this error is handled through LSP's normal response error scheme, so it won't "crash" the server.
If the error persists, please report it here or in a separate issue.

**Comment by clason** [comment]
> Regarding the "File cache not found" error, I still couldn't reproduce it on my end, so I haven't made any critical fixes.

Still happens, and not a flake (just re-loading the file with `:e` is enough to trigger it consistently in Neovim):
```
jetls: -32803: File cache for file:///Users/xxx/xxx.jl is not found
Press ENTER or type command to continue
```

As you can see, since it's treated as an error, it's surfaced as such and blocking the editor. Very annoying.

(Although now that the diagnostic reporting is fixed, this is less of an issue because I don't need to reload to fix false positives.)

**Comment by aviatesk** [comment]
https://github.com/aviatesk/JETLS.jl/pull/362 should fix the error entirely. Will be available from the new release, which I plan to release today.
