### ISSUE TITLE
ERROR: KeyError: key

### ISSUE THREAD

**Issue by ufechner7** [aviatesk/JETLS.jl#327]
If I checkout the package KiteUtils.jl
```
git clone https://github.com/OpenSourceAWE/KiteUtils.jl
cd KiteUtils.jl
julia -e 'using Pkg; Pkg.update()'
```
and then open the folder KiteUtils.jl in VSCode, and then open the file `src/KiteUtils.jl` and then wait, I get the following error:
```
[jetls-client] Auto-selected communication channel: pipe
[jetls-client] Using communication channel: pipe
[jetls-client] Server listening on Unix domain socket: /tmp/jetls-121295-1764096019044.sock
[jetls-client] Starting JETLS...
[jetls-client] JETLS connected!
[JETLS-stderr] ┌ Info: Connected to Unix domain socket
[JETLS-stderr] └   pipe_connect_path = "/tmp/jetls-121295-1764096019044.sock"
[JETLS-stderr] ┌ Info: Running JETLS with the following setup:
[JETLS-stderr] │   Sys.BINDIR = "/home/ufechner/.julia/juliaup/julia-1.12.2+0.x64.linux.gnu/bin"
[JETLS-stderr] │   pkgdir(JETLS) = "/home/ufechner/.julia/packages/JETLS/M2xQU"
[JETLS-stderr] │   Threads.nthreads() = 16
[JETLS-stderr] │   JETLS_DEV_MODE = false
[JETLS-stderr] │   JETLS_TEST_MODE = false
[JETLS-stderr] └   JETLS_DEBUG_LOWERING = false
[jetls-client] JETLS is ready!
[JETLS-stderr] ┌ Error: Error in `execute_analysis_request` for 
[JETLS-stderr] │   request = JETLS.AnalysisRequest(JETLS.PackageSourceAnalysisEntry("/home/ufechner/repos/KiteUtils.jl/Project.toml", file:///home/ufechner/repos/KiteUtils.jl/src/KiteUtils.jl, Base.PkgId(Base.UUID("90980105-b163-44e5-ba9f-8b1c83bb0533"), "KiteUtils")), file:///home/ufechner/repos/KiteUtils.jl/src/KiteUtils.jl, 0, JETLS.CancellableToken("##WorkDoneProgressCreateRequest_request_analysis_on_open!#297", JETLS.CancelFlag(false)), true, nothing, Base.Event(Base.GenericCondition(ReentrantLock()), false, false))
[JETLS-stderr] └ @ JETLS ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:172
[JETLS-stderr] ERROR: KeyError: key
[JETLS-stderr] file://
[JETLS-stderr] /home/ufechner/.julia/packages/Parameters/MK0O4/src/Parameters.jl not found
[JETLS-stderr] 
[JETLS-stderr] Stacktrace:
[JETLS-stderr]   [1] getindex
[JETLS-stderr]     @ ./dict.jl:477
[JETLS-stderr]  [inlined]
[JETLS-stderr]   [2]
[JETLS-stderr] jet_result_to_diagnostics!(uri2diagnostics::Dict{LSP.URIs2.URI, Vector{LSP.Diagnostic}}, result::JET.JETToplevelResult{JETLS.Analyzer.LSAnalyzer, @Kwargs{concretization_patterns::Vector{Symbol}, analyze_from_definitions::Bool, toplevel_logger::Nothing}})
[JETLS-stderr]     @ JETLS
[JETLS-stderr]  ~/.julia/packages/JETLS/M2xQU/src/diagnostics.jl:319
[JETLS-stderr]   [3] jet_result_to_diagnostics
[JETLS-stderr]     @ ~/.julia/packages/JETLS/M2xQU/src/diagnostics.jl:286 [inlined]
[JETLS-stderr]   [4]
[JETLS-stderr] new_analysis_result(request::JETLS.AnalysisRequest, result::JET.JETToplevelResult{JETLS.Analyzer.LSAnalyzer, @Kwargs{concretization_patterns::Vector{Symbol}, analyze_from_definitions::Bool, toplevel_logger::Nothing}})
[JETLS-stderr] 
[JETLS-stderr]     @ JETLS
[JETLS-stderr] ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:305
[JETLS-stderr] 
[JETLS-stderr]  [5]
[JETLS-stderr] execute_analysis_request(server::JETLS.Server{Returns{Nothing}}, request::JETLS.AnalysisRequest)
[JETLS-stderr]     @ JETLS ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:386
[JETLS-stderr]   [6] macro expansion
[JETLS-stderr]     @ ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:170 [inlined]
[JETLS-stderr]   [7] macro expansion
[JETLS-stderr]     @ ./some.jl:158 [inlined]
[JETLS-stderr]   [8]
[JETLS-stderr] resolve_analysis_request(server::JETLS.Server{Returns{Nothing}}, request::JETLS.AnalysisRequest)
[JETLS-stderr]     @ JETLS ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:169
[JETLS-stderr]   [9] macro expansion
[JETLS-stderr]     @ ~/.julia/packages/JETLS/M2xQU/src/utils/general.jl:106 [inlined]
[JETLS-stderr]  [10]
[JETLS-stderr] analysis_worker(server::JETLS.Server{Returns{Nothing}})
[JETLS-stderr]     @ JETLS ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:157
[JETLS-stderr]  [11]
[JETLS-stderr] (::JETLS.var"#start_analysis_workers!##0#start_analysis_workers!##1"{JETLS.Server{Returns{Nothing}}})()
[JETLS-stderr]     @ JETLS
[JETLS-stderr] ~/.julia/packages/JETLS/M2xQU/src/analysis/full-analysis.jl:4
```
This is the core of the error message:
```
[JETLS-stderr] file://
[JETLS-stderr] /home/ufechner/.julia/packages/Parameters/MK0O4/src/Parameters.jl not found
```
But the file exists:
```
ufechner@framework:~$ ls -la  /home/ufechner/.julia/packages/Parameters/MK0O4/src/Parameters.jl
-r--r--r-- 1 ufechner ufechner 20924 mei 13  2025 /home/ufechner/.julia/packages/Parameters/MK0O4/src/Parameters.jl
```
Any idea?

I am using the latest version from 25 Nov 2025.

**Comment by ufechner7** [comment]
Still the same error with the latest version of JETLS. Can you reproduce the problem?

**Comment by aviatesk** [comment]
This should be fixed in the next release `2025-12-05`.

**Comment by ufechner7** [comment]
I tested the latest version, and on one PC it works fine now, but on my laptop it still fails. Perhaps I have to delete a cache file?

**Comment by aviatesk** [comment]
Probably you need to restart your client or something.

**Comment by ufechner7** [comment]
Doesn't help:
```
[jetls-client] Auto-selected communication channel: pipe
[jetls-client] Using communication channel: pipe
[jetls-client] Server listening on Unix domain socket: /tmp/jetls-36284-1764966235009.sock
[jetls-client] Starting JETLS...
[jetls-client] JETLS connected!
[JETLS-stderr] ┌ Info: Connected to Unix domain socket
[JETLS-stderr] └   pipe_connect_path = "/tmp/jetls-36284-1764966235009.sock"
[JETLS-stderr] ┌ Info: Running JETLS with the following setup:
[JETLS-stderr] │   Sys.BINDIR = "/home/ufechner/.julia/juliaup/julia-1.12.2+0.x64.linux.gnu/bin"
[JETLS-stderr] │   pkgdir(JETLS) = "/home/ufechner/.julia/packages/JETLS/nM5j7"
[JETLS-stderr] │   Threads.nthreads() = 16
[JETLS-stderr] │   JETLS_VERSION = "2025-12-05"
[JETLS-stderr] │   JETLS_DEV_MODE = false
[JETLS-stderr] │   JETLS_TEST_MODE = false
[JETLS-stderr] └   JETLS_DEBUG_LOWERING = false
[jetls-client] JETLS is ready! (JETLS [version: 2025-12-05])
[JETLS-stderr] ┌ Error: Error in `execute_analysis_request` for 
[JETLS-stderr] │   request = JETLS.AnalysisRequest(JETLS.PackageSourceAnalysisEntry("/home/ufechner/repos/KiteModels.jl/Project.toml", file:///home/ufechner/repos/KiteModels.jl/src/KiteModels.jl, Base.PkgId(Base.UUID("b94af626-7959-4878-9336-2adc27959007"), "KiteModels")), file:///home/ufechner/repos/KiteModels.jl/src/KiteModels.jl, 0, JETLS.CancellableToken("##AnalysisProgress#302", JETLS.CancelFlag(false)), true, nothing, Base.Event(Base.GenericCondition(ReentrantLock()), false, false))
[JETLS-stderr] └ @ JETLS ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:321
[JETLS-stderr] ERROR: KeyError: key
[JETLS-stderr] file:///home/ufechner/.julia/packages/Parameters/MK0O4/src/Parameters.jl not found
[JETLS-stderr] 
[JETLS-stderr] Stacktrace:
[JETLS-stderr]  [1]
[JETLS-stderr]  getindex
[JETLS-stderr]    @ ./
[JETLS-stderr] dict.jl:477 [inlined]
[JETLS-stderr]  [2]
[JETLS-stderr] jet_result_to_diagnostics!(uri2diagnostics::Dict{LSP.URIs2.URI, Vector{LSP.Diagnostic}}, result::JET.JETToplevelResult{JETLS.Analyzer.LSAnalyzer, @Kwargs{concretization_patterns::Vector{Symbol}, analyze_from_definitions::Bool, toplevel_logger::Nothing}})
[JETLS-stderr]    @ JETLS ~/.julia/packages/JETLS/nM5j7/src/diagnostics.jl:319
[JETLS-stderr] [3] jet_result_to_diagnostics
[JETLS-stderr]    @ ~/.julia/packages/JETLS/nM5j7/src/diagnostics.jl:286 [inlined]
[JETLS-stderr]  [4]
[JETLS-stderr] new_analysis_result(request::JETLS.AnalysisRequest, result::JET.JETToplevelResult{JETLS.Analyzer.LSAnalyzer, @Kwargs{concretization_patterns::Vector{Symbol}, analyze_from_definitions::Bool, toplevel_logger::Nothing}})
[JETLS-stderr]    @ JETLS
[JETLS-stderr] ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:526
[JETLS-stderr]  [5]
[JETLS-stderr] execute_analysis_request(server::JETLS.Server{Returns{Nothing}}, request::JETLS.AnalysisRequest)
[JETLS-stderr] 
[JETLS-stderr]    @ JETLS ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:469
[JETLS-stderr]  [6]
[JETLS-stderr] resolve_analysis_request(server::JETLS.Server{Returns{Nothing}}, request::JETLS.AnalysisRequest)
[JETLS-stderr]    @ JETLS ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:319
[JETLS-stderr]  [7] macro expansion
[JETLS-stderr]    @ ~/.julia/packages/JETLS/nM5j7/src/utils/general.jl:106 [inlined]
[JETLS-stderr]  [8]
[JETLS-stderr] analysis_worker(server::JETLS.Server{Returns{Nothing}})
[JETLS-stderr] 
[JETLS-stderr]    @
[JETLS-stderr] JETLS ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:115
[JETLS-stderr]  [9]
[JETLS-stderr] (::JETLS.var"#start_analysis_workers!##0#start_analysis_workers!##1"{JETLS.Server{Returns{Nothing}}})()
[JETLS-stderr] 
[JETLS-stderr]    @ JETLS ~/.julia/packages/JETLS/nM5j7/src/analysis/full-analysis.jl:101
```
The file exists:
```
ufechner@framework:~/.julia/packages/Parameters/MK0O4/src$ ls -la
total 32
drwxrwxr-x 2 ufechner ufechner  4096 dec  3 10:46 .
drwxrwxr-x 7 ufechner ufechner  4096 mei 13  2025 ..
-r--r--r-- 1 ufechner ufechner 20924 mei 13  2025 Parameters.jl
ufechner@framework:~/.julia/packages/Parameters/MK0O4/src$ 
```
Strange:
This error happens only with the package KiteModels.jl, not when using the package KiteUtils.jl.

**Comment by aviatesk** [comment]
Ah, this is really different error. Should still be kept open.
